name = "livraison-api"
main = "src/index.ts"
compatibility_date = "2026-08-29"

[[d1_databases]]
binding = "DB"
database_name = "livraison-prod"
database_id = "d60dbbab-c35d-4984-acb5-dc1018fe56a6"

[vars]
APP_NAME = "وصلة"
